apiVersion: apps/v1
kind: Deployment
metadata:
  name: christanyk-nginx-deployment
  namespace: christanyk-eks-activity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: christanyk-nginx-service-account  # Add this line
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

